### ISSUE TITLE
Switch current view to OnionSkin view, button on UI

### ISSUE THREAD

**Issue by alfsici** [Viele/onionSkinRenderer#11]
I tought, it would make things faster to have 1  toggle button on the onion skin UI , that directly switches the current viewport between Vp2, and OnionSkin render, so while animating i can simply use 1 UI button to take care of it.

**Comment by Viele** [comment]
implemented.
Note this only works when toggling from viewport 2.0
It also saves the viewport you toggled.
So in case you have two modelling views, where one is your controller less camera view and one is the one you work in, it will toggle the one you set to onionSkinRenderer last
This breaks of course when having multiple windows with onion skin renderer, but then it breaks anyway, because that's not supported
